name: Compile ZSign for Linux

on: push

env:
  BUILD_TYPE: Release
  VERBOSE: 1

jobs:
  build-zsign:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies 
        run: |
          sudo add-apt-repository ppa:xmake-io/xmake
          sudo apt-get update && sudo apt-get install -y git wget zip unzip build-essential checkinstall zlib1g-dev libssl-dev
      - name: Compile zsign
        run: |
          xmake
          xmake install -o build
      - uses: actions/upload-artifact@v3
        with:
          name: zsign
          path: |
            ${{github.workspace}}/build/bin/zsign
